name: Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image
      run: |
        IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t $IMAGE_TAG .

    - name: Push image
      run: docker push $IMAGE_TAG

    - name: Update GitOps repo
      uses: actions/checkout@v4
      with:
        repository: jinalbabariya/myapp-gitops
        token: ${{ secrets.GITHUB_TOKEN }}
        path: myapp-gitops

    - name: Update image tag
      run: |
        sed -i "s|image: .*|image: $IMAGE_TAG|g" myapp-gitops/environments/dev/deployment.yaml
        sed -i "s|image: .*|image: $IMAGE_TAG|g" myapp-gitops/environments/staging/deployment.yaml
        sed -i "s|image: .*|image: $IMAGE_TAG|g" myapp-gitops/environments/prod/deployment.yaml

    - name: Commit changes
      env:
        PAT_TOKEN: ${{ secrets.GITOPS_PAT }}
      run: |
        git clone https://$PAT_TOKEN@github.com/jinalbabariya/myapp-gitops.git myapp-gitops-temp
        cd myapp-gitops-temp

        find . -type f -name "*.yaml" -print0 | while IFS= read -r -d '' file; do
        sed -i "s|image: ghcr.io.*/myapp:.*|image: $IMAGE_TAG|g" "$file"
        done

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Update image to $IMAGE_TAG" || echo "No changes"
        git push origin HEAD:main

        if git diff --quiet; then
          echo "No changes detected. Nothing to commit."
        else
          git add .
          git commit -m "Update myapp image to $IMAGE_TAG"
          git push origin HEAD:main
          echo "Changes committed and pushed!"
        fi
